export const MAIN_CARD = 'MAIN_CARD';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const RESET_FILTER = 'RESET_FILTER';
export const SUBMIT_FILTER = 'SUBMIT_FILTER';
export const REQUEST_CARD = 'REQUEST_CARD';
export const REQUEST_CARD_SUCCESS = 'REQUEST_CARD_SUCCESS';
export const REQUEST_CARD_FAIL = 'REQUEST_CARD_FAIL';